name: Update Badges
on:
  workflow_dispatch:
jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # --------------------------
    steps:
      - uses: actions/checkout@v3
      - name: Badges - Readme Action
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: mr-akarat-gobkuea
          NUMBER_LAST_BADGES: 0
