name: Update Badges
on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Badges - Readme Action
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: mr-akarat-gobkuea 
          NUMBER_LAST_BADGES: 0
